apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: burny-api-dev
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: "turing-reach-451305-f4:asia-northeast1:dev-postgres-instance"
    spec:
      serviceAccountName: cloud-run-service@turing-reach-451305-f4.iam.gserviceaccount.com
      containers:
      - image: asia-northeast1-docker.pkg.dev/turing-reach-451305-f4/dev-cloud-run/api
        env:
          - name: HOST
            value: "0.0.0.0"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: latest
                name: db_user
          - name: DB_PASS
            valueFrom:                  
              secretKeyRef:
                key: latest
                name: db_password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                key: latest
                name: db_name 
          - name: DB_INSTANCE_CONNECTION_NAME
            valueFrom:            
              secretKeyRef:
                key: latest
                name: db_instance_connection_name

