package main

import (
	"log"
	"net/http"

	"github.com/Tomoki108/burny/handler"
	"github.com/Tomoki108/burny/infrastructure"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"

	echoSwagger "github.com/swaggo/echo-swagger"
	_ "github.com/swaggo/echo-swagger/example/docs" // docs is generated by Swag CLI, you have to import it.
	_ "github.com/swaggo/files"                     // swagger embed files
)

type data struct {
	Date        string `json:"date"`
	SolarPanels int    `json:"SolarPanels"`
	Inverters   int    `json:"Inverters"`
}

// @title           Swagger Example API2
// @version         1.0
// @description     This is a sample server celler server.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /api/v1

// @securityDefinitions.basic  BasicAuth

// @externalDocs.description  OpenAPI
// @externalDocs.url          https://swagger.io/resources/open-api/
func main() {
	// Echoのインスタンス作成
	e := echo.New()

	// Swaggerの設定
	e.GET("/swagger/*", echoSwagger.WrapHandler)

	// ミドルウェアの設定
	e.Use(middleware.Logger())
	e.Use(middleware.Recover())

	// DB接続
	if err := infrastructure.ConnectDB(); err != nil {
		log.Fatal(err.Error())
	}

	// ルートエンドポイント
	e.GET("/", func(c echo.Context) error {
		return c.String(http.StatusOK, "Hello, World!")
	})

	projectHandler := handler.ProjectHandler{
		Repo: infrastructure.NewProjectRepository(),
	}
	sprintHandler := handler.SprintHandler{
		Repo: infrastructure.NewSprintRepository(),
	}

	// エンドポイントの追加
	e.GET("/projects", projectHandler.List)
	e.POST("/projects", projectHandler.Create)
	e.GET("/projects/:id", projectHandler.Get)
	e.PUT("/projects/:id", projectHandler.Update)
	e.DELETE("/projects/:id", projectHandler.Delete)

	e.GET("/sprints", sprintHandler.List)
	e.PUT("/sprints/:id", sprintHandler.Update)

	e.GET("test", func(c echo.Context) error {
		list := []data{
			{Date: "Jan 22", SolarPanels: 2890, Inverters: 2338},
			{Date: "Feb 22", SolarPanels: 2756, Inverters: 2103},
			{Date: "Mar 22", SolarPanels: 3322, Inverters: 2194},
			{Date: "Apr 22", SolarPanels: 3470, Inverters: 2108},
			{Date: "May 22", SolarPanels: 3475, Inverters: 1812},
			{Date: "Jun 22", SolarPanels: 3129, Inverters: 1726},
			{Date: "Jul 22", SolarPanels: 3490, Inverters: 1982},
			{Date: "Aug 22", SolarPanels: 2903, Inverters: 2012},
		}

		return c.JSON(http.StatusOK, list)
	})

	// CORSの設定。localhost（別のポート）からの通信を許可するだけならこれで十分らしい。
	// https://qiita.com/sola-msr/items/828e2eb45cf05b1a2ad4
	e.Use(middleware.CORS())
	// サーバーの開始
	e.Logger.Fatal(e.Start(":1323"))
}
