name: API Deployment to Cloud Run

on:
  push:
    branches:
      - main
      - organize-dns-records # for test
    paths:
      - "api/**"
      - ".github/workflows/api_deployment.yml"

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: asia-northeast1-docker.pkg.dev/turing-reach-451305-f4/cloud-run/api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/810897677786/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
          service_account: github-actions-service@turing-reach-451305-f4.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 363.0.0"

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build and Push Docker Image
        working-directory: api
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy burny-api \
            --image ${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --region asia-northeast1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars=HOST=dev.api.burny.page \
            --update-secrets=DB_HOST=db_host:latest, \
            DB_NAME=db_name:latest, \
            DB_USER=db_user:latest, \
            DB_PASS=db_pass:latest
