name: API Deployment to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - ".github/workflows/api_deployment.yml"

jobs:
  deploy:
    permissions:
        contents: 'read'
        id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/810897677786/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-service@turing-reach-451305-f4.iam.gserviceaccount.com
  
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
            version: '>= 363.0.0'

      - name: Retrieve Secrets from Secret Manager
        run: |
          export DB_HOST=$(gcloud secrets versions access latest --secret=db_host)
          export DB_NAME=$(gcloud secrets versions access latest --secret=db_name)
          export DB_USER=$(gcloud secrets versions access latest --secret=db_user)
          export DB_PASS=$(gcloud secrets versions access latest --secret=db_password)
          
          echo "DB_HOST=$DB_HOST" >> $GITHUB_ENV
          echo "DB_NAME=$DB_NAME" >> $GITHUB_ENV
          echo "DB_USER=$DB_USER" >> $GITHUB_ENV
          echo "DB_PASS=$DB_PASS" >> $GITHUB_ENV

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x skaffold
          sudo mv skaffold /usr/local/bin/

          ## kome
      - name: Deploy to Cloud Run via Skaffold
        working-directory: api
        env:
          DB_HOST: ${{ env.DB_HOST }}
          DB_NAME: ${{ env.DB_NAME }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASS: ${{ env.DB_PASS }}
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev
          skaffold run