name: API Scenario Test

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "api/**"
      - ".github/workflows/api_scenario.yml"
  pull_request:
    paths:
      - "api/**"
      - ".github/workflows/api_scenario.yml"

defaults:
  run:
    working-directory: api

env:
  TZ: Asia/Tokyo

jobs:
  scenario-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose environment
        run: |
          docker compose -f compose.yml up -d
          # Wait for postgres container to be ready
          sleep 10

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Install dependencies
        run: go mod download

      - name: Run Scenario tests
        run: go test -v ./scenario/...

      - name: Shutdown Docker Compose services
        if: always()
        run: docker compose -f compose.yml down
