name: API Deployment to Cloud Run

on:
  workflow_run:
    workflows: ["API Scenario Test"]
    branches: [main, dev]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: asia-northeast1-docker.pkg.dev/turing-reach-451305-f4/cloud-run/api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set environment variables based on branch
        run: |
          if [[ "${{ github.event.workflow_run.head_branch }}" == "main" ]]; then
            echo "HOST=api.burny.page" >> $GITHUB_ENV
          else
            echo "HOST=dev-api.burny.page" >> $GITHUB_ENV
          fi

      # prod project is not set up yet
      # - name: Authenticate with Google Cloud (prod project)
      #   if: ${{ github.event.workflow_run.head_branch }} == 'main'
      #   uses: google-github-actions/auth@v2
      #   with:
      #     workload_identity_provider: projects/810897677786/locations/global/workloadIdentityPools/github-actions-pool-01/providers/github-actions-provider-01
      #     service_account: github-actions-service@turing-reach-451305-f4.iam.gserviceaccount.com

      - name: Authenticate with Google Cloud (dev project)
        if: ${{ github.event.workflow_run.head_branch }} == 'dev'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/810897677786/locations/global/workloadIdentityPools/github-actions-pool-01/providers/github-actions-provider-01
          service_account: github-actions-service@turing-reach-451305-f4.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: "514.0.0"

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build and Push Docker Image
        working-directory: api
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ github.event.workflow_run.head_sha }} .
          docker push ${{ env.IMAGE_NAME }}:${{ github.event.workflow_run.head_sha }}
          docker tag ${{ env.IMAGE_NAME }}:${{ github.event.workflow_run.head_sha }} ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy burny-api \
            --image ${{ env.IMAGE_NAME }}:${{ github.event.workflow_run.head_sha }} \
            --region asia-northeast1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars=HOST=${{ env.HOST }} \
            --update-secrets=DB_HOST=db_host:latest,DB_NAME=db_name:latest,DB_USER=db_user:latest,DB_PASSWORD=db_password:latest
