name: API Deployment to Cloud Run

on:
  workflow_run:
    workflows: ["API Scenario Test"]
    branches: [main, dev]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Production
        if: ${{ github.event.workflow_run.head_branch == 'main' || github.ref_name == 'main' }} # ref is for workflow_dispatch (manual) trigger
        uses: ./.github/actions/api_deployment
        with:
          domain: ${{ secrets.PROD_API_HOST }}
          workload-identity-provider: ${{ secrets.PROD_GITHUB_WIP }}
          service-account: ${{ secrets.PROD_GITHUB_SA }}
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}
          image-name: asia-northeast1-docker.pkg.dev/burny-prod/cloud-run/api

      - name: Deploy to Development
        if: ${{ github.event.workflow_run.head_branch == 'dev' || github.ref_name == 'dev' }}
        uses: ./.github/actions/api_deployment
        with:
          domain: ${{ secrets.DEV_API_HOST }}
          workload-identity-provider: ${{ secrets.DEV_GITHUB_WIP }}
          service-account: ${{ secrets.DEV_GITHUB_SA }}
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}
          image-name: asia-northeast1-docker.pkg.dev/turing-reach-451305-f4/cloud-run/api
