name: Web Deployment to GCS
on:
  workflow_run:
    workflows: ["Web Scenario Test"]
    branches: [main, dev]
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Production
        if: ${{ github.event.workflow_run.head_branch == 'main' }}
        uses: ./.github/actions/web-deployment
        with:
          bucket-name: ${{ secrets.PROD_WEB_BUCKET }}
          api-host: https://${{ secrets.PROD_API_HOST }}/api/v1
          workload-identity-provider: temp_not_exist_yet
          service-account: temp_not_exist_yet
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Deploy to Development
        if: ${{ github.event.workflow_run.head_branch == 'dev' }}
        uses: ./.github/actions/web-deployment
        with:
          bucket-name: ${{ secrets.DEV_WEB_BUCKET }}
          api-host: https://${{ secrets.DEV_API_HOST }}/api/v1
          workload-identity-provider: projects/810897677786/locations/global/workloadIdentityPools/github-actions-pool-01/providers/github-actions-provider-01
          service-account: github-actions-service@turing-reach-451305-f4.iam.gserviceaccount.com
          ref: ${{ github.event.workflow_run.head_sha }}
