name: Web Scenario Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    paths:
      - "web/**"
      - ".github/workflows/web_scenario.yml"
  workflow_dispatch:

jobs:
  scenario-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        id: setup_node_id
        with:
          node-version: "23"

      - name: Install dependencies
        run: npm ci

      - name: Cache Playwright dependencies
        uses: actions/cache@v3
        id: playwright_cache
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('web/package-lock.json') }}

      - name: Install Playwright
        if: ${{ steps.playwright_cache.outputs.cache-hit != 'true' }}
        run: npx playwright install --with-deps

      - name: Start Vite server in the background
        run: |
          npx vite --port 5179 &
          echo "Waiting for the server to start..."
          sleep 5

      - name: Run tests
        run: npm run test

      - name: Upload test results and screenshots
        uses: actions/upload-artifact@v4
        if: always() # Always upload artifacts even if tests fail
        with:
          name: test-results
          path: web/test-results/
          retention-days: 7
